self.spellcaster_toggleButton = self.findChild(QtWidgets.QPushButton, 'spellcaster_toggleButton')
self.add_button = self.findChild(QtWidgets.QPushButton, 'add_button')
self.newCharacter_button = self.findChild(QtWidgets.QPushButton, "newCharacter_button")
self.addMagicItem_button = self.findChild(QtWidgets.QPushButton, 'addMagicItem_button')
self.remove_button = self.findChild(QtWidgets.QPushButton, 'remove_button')
self.removeMagicItem_button = self.findChild(QtWidgets.QPushButton, 'removeMagicItem_button')
self.addWeapon_button = self.findChild(QtWidgets.QPushButton, 'addWeapon_button')
self.removeWeapon_button = self.findChild(QtWidgets.QPushButton, 'removeWeapon_button')
self.saveCharacter_button = self.findChild(QtWidgets.QPushButton,'saveCharacter_button')
self.removeCharacter_button = self.findChild(QtWidgets.QPushButton,'removeCharacter_button')
self.openCharacter_button = self.findChild(QtWidgets.QPushButton,'openCharacter_button')
self.levelFourHelp_button3 = self.findChild(QtWidgets.QPushButton, 'levelFourHelp_button3')
self.levelFourHelp_button1 = self.findChild(QtWidgets.QPushButton, 'levelFourHelp_button1')
self.levelFourHelp_button4 = self.findChild(QtWidgets.QPushButton, 'levelFourHelp_button4')
self.levelFourHelp_button5 = self.findChild(QtWidgets.QPushButton, 'levelFourHelp_button5')
self.levelFourHelp_button2 = self.findChild(QtWidgets.QPushButton, 'levelFourHelp_button2')
self.levelFourHelp_button7 = self.findChild(QtWidgets.QPushButton, 'levelFourHelp_button7')
self.levelFourHelp_button6 = self.findChild(QtWidgets.QPushButton, 'levelFourHelp_button6')
self.levelFiveHelp_button4 = self.findChild(QtWidgets.QPushButton, 'levelFiveHelp_button4')
self.levelFiveHelp_button5 = self.findChild(QtWidgets.QPushButton, 'levelFiveHelp_button5')
self.levelFiveHelp_button7 = self.findChild(QtWidgets.QPushButton, 'levelFiveHelp_button7')
self.levelFiveHelp_button6 = self.findChild(QtWidgets.QPushButton, 'levelFiveHelp_button6')
self.levelFiveHelp_button2 = self.findChild(QtWidgets.QPushButton, 'levelFiveHelp_button2')
self.levelFiveHelp_button1 = self.findChild(QtWidgets.QPushButton, 'levelFiveHelp_button1')
self.levelFiveHelp_button3 = self.findChild(QtWidgets.QPushButton, 'levelFiveHelp_button3')
self.levelSixHelp_button7 = self.findChild(QtWidgets.QPushButton, 'levelSixHelp_button7')
self.levelSixHelp_button6 = self.findChild(QtWidgets.QPushButton, 'levelSixHelp_button6')
self.levelSixHelp_button5 = self.findChild(QtWidgets.QPushButton, 'levelSixHelp_button5')
self.levelSixHelp_button4 = self.findChild(QtWidgets.QPushButton, 'levelSixHelp_button4')
self.levelSixHelp_button3 = self.findChild(QtWidgets.QPushButton, 'levelSixHelp_button3')
self.levelSixHelp_button2 = self.findChild(QtWidgets.QPushButton, 'levelSixHelp_button2')
self.levelSixHelp_button1 = self.findChild(QtWidgets.QPushButton, 'levelSixHelp_button1')
self.levelSevenHelp_button6 = self.findChild(QtWidgets.QPushButton, 'levelSevenHelp_button6')
self.levelSevenHelp_button7 = self.findChild(QtWidgets.QPushButton, 'levelSevenHelp_button7')
self.levelSevenHelp_button2 = self.findChild(QtWidgets.QPushButton, 'levelSevenHelp_button2')
self.levelSevenHelp_button1 = self.findChild(QtWidgets.QPushButton, 'levelSevenHelp_button1')
self.levelSevenHelp_button3 = self.findChild(QtWidgets.QPushButton, 'levelSevenHelp_button3')
self.levelSevenHelp_button4 = self.findChild(QtWidgets.QPushButton, 'levelSevenHelp_button4')
self.levelSevenHelp_button5 = self.findChild(QtWidgets.QPushButton, 'levelSevenHelp_button5')
self.levelOneHelp_button2_3 = self.findChild(QtWidgets.QPushButton, 'levelOneHelp_button2_3')
self.levelOneHelp_button3 = self.findChild(QtWidgets.QPushButton, 'levelOneHelp_button3')
self.levelOneHelp_button4_3 = self.findChild(QtWidgets.QPushButton, 'levelOneHelp_button4_3')
self.levelOneHelp_button5 = self.findChild(QtWidgets.QPushButton, 'levelOneHelp_button5')
self.levelOneHelp_button6 = self.findChild(QtWidgets.QPushButton, 'levelOneHelp_button6')
self.levelOneHelp_button1 = self.findChild(QtWidgets.QPushButton, 'levelOneHelp_button1')
self.levelOneHelp_button7 = self.findChild(QtWidgets.QPushButton, 'levelOneHelp_button7')
self.levelZeroHelp_button1 = self.findChild(QtWidgets.QPushButton, 'levelZeroHelp_button1')
self.levelZeroHelp_button2 = self.findChild(QtWidgets.QPushButton, 'levelZeroHelp_button2')
self.levelZeroHelp_button6 = self.findChild(QtWidgets.QPushButton, 'levelZeroHelp_button6')
self.levelZeroHelp_button4 = self.findChild(QtWidgets.QPushButton, 'levelZeroHelp_button4')
self.levelZeroHelp_button7 = self.findChild(QtWidgets.QPushButton, 'levelZeroHelp_button7')
self.levelZeroHelp_button5 = self.findChild(QtWidgets.QPushButton, 'levelZeroHelp_button5')
self.levelZeroHelp_button3 = self.findChild(QtWidgets.QPushButton, 'levelZeroHelp_button3')
self.levelZeroHelp_button1 = self.findChild(QtWidgets.QPushButton, 'levelZeroHelp_button1')
self.levelZeroHelp_button3 = self.findChild(QtWidgets.QPushButton, 'levelZeroHelp_button3')
self.levelZeroHelp_button6 = self.findChild(QtWidgets.QPushButton, 'levelZeroHelp_button6')
self.levelZeroHelp_button2 = self.findChild(QtWidgets.QPushButton, 'levelZeroHelp_button2')
self.levelZeroHelp_button5 = self.findChild(QtWidgets.QPushButton, 'levelZeroHelp_button5')
self.levelZeroHelp_button4 = self.findChild(QtWidgets.QPushButton, 'levelZeroHelp_button4')
self.levelZeroHelp_button7 = self.findChild(QtWidgets.QPushButton, 'levelZeroHelp_button7')
self.levelOneHelp_button5_4 = self.findChild(QtWidgets.QPushButton, 'levelOneHelp_button5_4')
self.levelOneHelp_button6 = self.findChild(QtWidgets.QPushButton, 'levelOneHelp_button6')
self.levelOneHelp_button1 = self.findChild(QtWidgets.QPushButton, 'levelOneHelp_button1')
self.levelOneHelp_button4 = self.findChild(QtWidgets.QPushButton, 'levelOneHelp_button4')
self.levelOneHelp_button2 = self.findChild(QtWidgets.QPushButton, 'levelOneHelp_button2')
self.levelOneHelp_button7 = self.findChild(QtWidgets.QPushButton, 'levelOneHelp_button7')
self.levelOneHelp_button3 = self.findChild(QtWidgets.QPushButton, 'levelOneHelp_button3')
self.levelEightHelp_button1 = self.findChild(QtWidgets.QPushButton, 'levelEightHelp_button1')
self.levelEightHelp_button3 = self.findChild(QtWidgets.QPushButton, 'levelEightHelp_button3')
self.levelEightHelp_button4 = self.findChild(QtWidgets.QPushButton, 'levelEightHelp_button4')
self.levelEightHelp_button6 = self.findChild(QtWidgets.QPushButton, 'levelEightHelp_button6')
self.levelEightHelp_button7 = self.findChild(QtWidgets.QPushButton, 'levelEightHelp_button7')
self.levelEightHelp_button5 = self.findChild(QtWidgets.QPushButton, 'levelEightHelp_button5')
self.levelEightHelp_button2 = self.findChild(QtWidgets.QPushButton, 'levelEightHelp_button2')
self.levelNineHelp_button3 = self.findChild(QtWidgets.QPushButton, 'levelNineHelp_button3')
self.levelNineHelp_button2 = self.findChild(QtWidgets.QPushButton, 'levelNineHelp_button2')
self.levelNineHelp_button4 = self.findChild(QtWidgets.QPushButton, 'levelNineHelp_button4')
self.levelNineHelp_button5 = self.findChild(QtWidgets.QPushButton, 'levelNineHelp_button5')
self.levelNineHelp_button6 = self.findChild(QtWidgets.QPushButton, 'levelNineHelp_button6')
self.levelNineHelp_button7 = self.findChild(QtWidgets.QPushButton, 'levelNineHelp_button7')
self.levelNineHelp_button1 = self.findChild(QtWidgets.QPushButton, 'levelNineHelp_button1')


#spin boxes (integer entry boxes)
self.XP_entry = self.findChild(QtWidgets.QSpinBox, 'XP_entry')
self.level_entry = self.findChild(QtWidgets.QSpinBox, 'level_entry')
self.proficiencyBonus_entry = self.findChild(QtWidgets.QSpinBox, 'proficiencyBonus_entry')
self.armorClass_entry = self.findChild(QtWidgets.QSpinBox, 'armorClass_entry')
self.typeOfHitDice_entry = self.findChild(QtWidgets.QSpinBox, 'typeOfHitDice_entry')
self.spinBox_3 = self.findChild(QtWidgets.QSpinBox, 'spinBox_3')
self.spinBox_4 = self.findChild(QtWidgets.QSpinBox, 'spinBox_4')
self.initiativeBoost_entry = self.findChild(QtWidgets.QSpinBox, 'initiativeBoost_entry')
self.speed_entry = self.findChild(QtWidgets.QSpinBox, 'speed_entry')
self.spinBox = self.findChild(QtWidgets.QSpinBox, 'spinBox')
self.strength_entry = self.findChild(QtWidgets.QSpinBox, 'strength_entry')
self.dexterity_entry = self.findChild(QtWidgets.QSpinBox, 'dexterity_entry')
self.wisdom_entry = self.findChild(QtWidgets.QSpinBox, 'wisdom_entry')
self.constitution_entry = self.findChild(QtWidgets.QSpinBox, 'constitution_entry')
self.intelligence_entry = self.findChild(QtWidgets.QSpinBox, 'intelligence_entry')
self.charisma_entry = self.findChild(QtWidgets.QSpinBox, 'charisma_entry')
self.cp_entry = self.findChild(QtWidgets.QSpinBox, 'cp_entry')
self.ep_entry = self.findChild(QtWidgets.QSpinBox, 'ep_entry')
self.sp_entry = self.findChild(QtWidgets.QSpinBox, 'sp_entry')
self.gp_entry = self.findChild(QtWidgets.QSpinBox, 'gp_entry')
self.pp_entry = self.findChild(QtWidgets.QSpinBox, 'pp_entry')
self.add_entry = self.findChild(QtWidgets.QSpinBox, 'add_entry')
self.remove_entry = self.findChild(QtWidgets.QSpinBox, 'remove_entry')
self.persuasionBoost_entry = self.findChild(QtWidgets.QSpinBox, 'persuasionBoost_entry')
self.perceptionBoost_entry = self.findChild(QtWidgets.QSpinBox, 'perceptionBoost_entry')
self.performanceBoost_entry = self.findChild(QtWidgets.QSpinBox, 'performanceBoost_entry')
self.religionBoost_entry = self.findChild(QtWidgets.QSpinBox, 'religionBoost_entry')
self.slightOfHandBoost_entry = self.findChild(QtWidgets.QSpinBox, 'slightOfHandBoost_entry')
self.stealthBoost_entry = self.findChild(QtWidgets.QSpinBox, 'stealthBoost_entry')
self.natureBoost_entry = self.findChild(QtWidgets.QSpinBox, 'natureBoost_entry')
self.survivalBoost_entry = self.findChild(QtWidgets.QSpinBox, 'survivalBoost_entry')
self.arcanaBoost_entry = self.findChild(QtWidgets.QSpinBox, 'arcanaBoost_entry')
self.athleticsBoost_entry = self.findChild(QtWidgets.QSpinBox, 'athleticsBoost_entry')
self.animalHandling_entry = self.findChild(QtWidgets.QSpinBox, 'animalHandling_entry')
self.insightBoost_entry = self.findChild(QtWidgets.QSpinBox, 'insightBoost_entry')
self.intimidationBoost_entry = self.findChild(QtWidgets.QSpinBox, 'intimidationBoost_entry')
self.deceptionBoost_entry = self.findChild(QtWidgets.QSpinBox, 'deceptionBoost_entry')
self.acrobaticsBoost_entry = self.findChild(QtWidgets.QSpinBox, 'acrobaticsBoost_entry')
self.medicineBoost_entry = self.findChild(QtWidgets.QSpinBox, 'medicineBoost_entry')
self.investigationBoost_entry = self.findChild(QtWidgets.QSpinBox, 'investigationBoost_entry')
self.historyBoost_entry = self.findChild(QtWidgets.QSpinBox, 'historyBoost_entry')
self.heightFeet_entry = self.findChild(QtWidgets.QSpinBox, 'heightFeet_entry')
self.heightInches_entry = self.findChild(QtWidgets.QSpinBox, 'heightInches_entry')
self.weightPounds_entry = self.findChild(QtWidgets.QSpinBox, 'weightPounds_entry')
self.age_entry = self.findChild(QtWidgets.QSpinBox, 'age_entry')
self.removeMagicItem_entry = self.findChild(QtWidgets.QSpinBox, 'removeMagicItem_entry')
self.removeWeapon_entry = self.findChild(QtWidgets.QSpinBox, 'removeWeapon_entry')


#labels
self.dndCharacterSheetViewer_label = self.findChild(QtWidgets.QLabel,'dndCharacterSheetViewer_label')
self.sheetName_label = self.findChild(QtWidgets.QLabel,'sheetName_label')
self.physicalAppearence_label = self.findChild(QtWidgets.QLabel, 'physicalAppearence_label')
self.race_label = self.findChild(QtWidgets.QLabel, 'race_label')
self.level_label = self.findChild(QtWidgets.QLabel, 'level_label')
self.characterName_label = self.findChild(QtWidgets.QLabel, 'characterName_label')
self.playerName_label = self.findChild(QtWidgets.QLabel, 'playerName_label')
self.class_label = self.findChild(QtWidgets.QLabel, 'class_label')
self.background_label = self.findChild(QtWidgets.QLabel, 'background_label')
self.XP_label = self.findChild(QtWidgets.QLabel, 'XP_label')
self.alignment_label = self.findChild(QtWidgets.QLabel, 'alignment_label')
self.proficiencyBonus_label = self.findChild(QtWidgets.QLabel, 'proficiencyBonus_label')
self.inspiration_label = self.findChild(QtWidgets.QLabel, 'inspiration_label')
self.fail_label = self.findChild(QtWidgets.QLabel, 'fail_label')
self.success_label = self.findChild(QtWidgets.QLabel, 'success_label')
self.deathSaves_label = self.findChild(QtWidgets.QLabel, 'deathSaves_label')
self.armorClass_label = self.findChild(QtWidgets.QLabel, 'armorClass_label')
self.armorType_label = self.findChild(QtWidgets.QLabel, 'armorType_label')
self.hitPoints_label = self.findChild(QtWidgets.QLabel, 'hitPoints_label')
self.maxHP_label = self.findChild(QtWidgets.QLabel, 'maxHP_label')
self.currentHP_label = self.findChild(QtWidgets.QLabel, 'currentHP_label')
self.tempHP_label = self.findChild(QtWidgets.QLabel, 'tempHP_label')
self.initiative_label = self.findChild(QtWidgets.QLabel, 'initiative_label')
self.initiativeScore_label = self.findChild(QtWidgets.QLabel, 'initiativeScore_label')
self.initiativeBoost_label = self.findChild(QtWidgets.QLabel, 'initiativeBoost_label')
self.initiativeScore_label = self.findChild(QtWidgets.QLabel, 'initiativeScore_label')
self.speed_label = self.findChild(QtWidgets.QLabel, 'speed_label')
self.hitDice_label = self.findChild(QtWidgets.QLabel, 'hitDice_label')
self.numberOfHitDice_label = self.findChild(QtWidgets.QLabel, 'numberOfHitDice_label')
self.dHitDice_label = self.findChild(QtWidgets.QLabel, 'dHitDice_label')
self.modifiers_label_upper = self.findChild(QtWidgets.QLabel, 'modifiers_label_upper')
self.dexteritySaveModifier_label = self.findChild(QtWidgets.QLabel, 'dexteritySaveModifier_label')
self.wisdomSaveModifier_label = self.findChild(QtWidgets.QLabel, 'wisdomSaveModifier_label')
self.charismaSaveModifier_label = self.findChild(QtWidgets.QLabel, 'charismaSaveModifier_label')
self.strengthSaveModifier_label = self.findChild(QtWidgets.QLabel, 'strengthSaveModifier_label')
self.intelligenceSaveModifier_label = self.findChild(QtWidgets.QLabel, 'intelligenceSaveModifier_label')
self.scores_label_upper = self.findChild(QtWidgets.QLabel, 'scores_label_upper')
self.constitution_label = self.findChild(QtWidgets.QLabel, 'constitution_label')
self.strength_modifier = self.findChild(QtWidgets.QLabel, 'strength_modifier')
self.constitution_modifier = self.findChild(QtWidgets.QLabel, 'constitution_modifier')
self.stats_label_upper = self.findChild(QtWidgets.QLabel, 'stats_label_upper')
self.intelligence_modifier = self.findChild(QtWidgets.QLabel, 'intelligence_modifier')
self.dexterity_modifier = self.findChild(QtWidgets.QLabel, 'dexterity_modifier')
self.wisdom_modifier = self.findChild(QtWidgets.QLabel, 'wisdom_modifier')
self.charisma_modifier = self.findChild(QtWidgets.QLabel, 'charisma_modifier')
self.constitutionSaveModifier_label = self.findChild(QtWidgets.QLabel, 'constitutionSaveModifier_label')
self.strength_label = self.findChild(QtWidgets.QLabel, 'strength_label')
self.dexterity_label = self.findChild(QtWidgets.QLabel, 'dexterity_label')
self.wisdom_label = self.findChild(QtWidgets.QLabel, 'wisdom_label')
self.intelligence_label = self.findChild(QtWidgets.QLabel, 'intelligence_label')
self.charisma_label = self.findChild(QtWidgets.QLabel, 'charisma_label')
self.saves_label_upper = self.findChild(QtWidgets.QLabel, 'saves_label_upper')
self.add_label = self.findChild(QtWidgets.QLabel, 'add_label')
self.remove_label = self.findChild(QtWidgets.QLabel, 'remove_label')
self.currency_labelsc = self.findChild(QtWidgets.QLabel, 'currency_labelsc')
self.proficiencies_label = self.findChild(QtWidgets.QLabel, 'proficiencies_label')
self.languages_label = self.findChild(QtWidgets.QLabel, 'languages_label')
self.misc_textArea = self.findChild(QtWidgets.QLabel, 'misc_textArea_3')
self.skills_label = self.findChild(QtWidgets.QLabel, 'skills_label')
self.athleticsModifier_label = self.findChild(QtWidgets.QLabel, 'athleticsModifier_label')
self.deceptionStatUsed_label = self.findChild(QtWidgets.QLabel, 'deceptionStatUsed_label')
self.acrobaticsStatUsed_label = self.findChild(QtWidgets.QLabel, 'acrobaticsStatUsed_label')
self.boost_label = self.findChild(QtWidgets.QLabel, 'boost_label')
self.medicineStatUsed_label = self.findChild(QtWidgets.QLabel, 'medicineStatUsed_label')
self.investigationModifier_label = self.findChild(QtWidgets.QLabel, 'investigationModifier_label')
self.acrobaticsModifier_label = self.findChild(QtWidgets.QLabel, 'acrobaticsModifier_label')
self.athleticsStatUsed_label = self.findChild(QtWidgets.QLabel, 'athleticsStatUsed_label')
self.investigationStatUsed_label = self.findChild(QtWidgets.QLabel, 'investigationStatUsed_label')
self.stat_label = self.findChild(QtWidgets.QLabel, 'stat_label')
self.intimidationStatUsed_label = self.findChild(QtWidgets.QLabel, 'intimidationStatUsed_label')
self.insightModifier_label = self.findChild(QtWidgets.QLabel, 'insightModifier_label')
self.arcanaStatUsed_label = self.findChild(QtWidgets.QLabel, 'arcanaStatUsed_label')
self.modifier_label = self.findChild(QtWidgets.QLabel, 'modifier_label')
self.historyModifier_label = self.findChild(QtWidgets.QLabel, 'historyModifier_label')
self.medicineModifier_label = self.findChild(QtWidgets.QLabel, 'medicineModifier_label')
self.personalityTraits_label = self.findChild(QtWidgets.QLabel, 'personalityTraits_label')
self.ideals_label = self.findChild(QtWidgets.QLabel, 'ideals_label')
self.bonds_label = self.findChild(QtWidgets.QLabel, 'bonds_label')
self.flaws_label = self.findChild(QtWidgets.QLabel, 'flaws_label')
self.equipment_label = self.findChild(QtWidgets.QLabel, 'equipment_label')
self.FeaturesAndTraits_label = self.findChild(QtWidgets.QLabel, 'FeaturesAndTraits_label')
self.physicalAppearence_label = self.findChild(QtWidgets.QLabel, 'physicalAppearence_label')
self.feet_label = self.findChild(QtWidgets.QLabel, 'feet_label')
self.inches_label = self.findChild(QtWidgets.QLabel, 'inches_label')
self.pounds_label = self.findChild(QtWidgets.QLabel, 'pounds_label')
self.eyes_label = self.findChild(QtWidgets.QLabel, 'eyes_label')
self.hair_label = self.findChild(QtWidgets.QLabel, 'hair_label')
self.miscPhysicalAppearenceNotes_label = self.findChild(QtWidgets.QLabel, 'miscPhysicalAppearenceNotes_label')
self.age_label = self.findChild(QtWidgets.QLabel, 'age_label')
self.weight_label = self.findChild(QtWidgets.QLabel, 'weight_label')
self.height_label = self.findChild(QtWidgets.QLabel, 'height_label')
self.treasureAndMagicItems_label = self.findChild(QtWidgets.QLabel, 'treasureAndMagicItems_label')
self.miscNotesLabel = self.findChild(QtWidgets.QLabel, 'miscNotesLabel')
self.characterBackstory_label = self.findChild(QtWidgets.QLabel, 'characterBackstory_label')
self.allieandOrganizations_label = self.findChild(QtWidgets.QLabel, 'allieandOrganizations_label')
self.lore_label = self.findChild(QtWidgets.QLabel, 'lore_label')
self.spellcasting_label = self.findChild(QtWidgets.QLabel, 'spellcasting_label')
self.spellAbilityValue_label = self.findChild(QtWidgets.QLabel, 'spellAbilityValue_label')
self.spellSaveDC_label = self.findChild(QtWidgets.QLabel, 'spellSaveDC_label')
self.spellAbility_label = self.findChild(QtWidgets.QLabel, 'spellAbility_label')
self.spellAttackBonus_label = self.findChild(QtWidgets.QLabel, 'spellAttackBonus_label')
self.spellSaveDCValue_label = self.findChild(QtWidgets.QLabel, 'spellSaveDCValue_label')
self.spellAttackBonusValue_label = self.findChild(QtWidgets.QLabel, 'spellAttackBonusValue_label')
self.spellScrollSpacer = self.findChild(QtWidgets.QLabel, 'spellScrollSpacer')

#line edit areas
self.race_entry = self.findChild(QtWidgets.QLineEdit, 'race_entry')
self.characterName_entry = self.findChild(QtWidgets.QLineEdit, 'characterName_entry')
self.background_entry = self.findChild(QtWidgets.QLineEdit, 'background_entry')
self.playerName_entry = self.findChild(QtWidgets.QLineEdit, 'playerName_entry')
self.class_entry = self.findChild(QtWidgets.QLineEdit, 'class_entry')
self.armorType_label = self.findChild(QtWidgets.QLineEdit, 'armorType_label')

#combo boxes (dropdown menues)
self.alignment_entry = self.findChild(QtWidgets.QComboBox, 'alignment_entry')
self.addType_entry = self.findChild(QtWidgets.QComboBox, 'addType_entry')
self.removeType_entry = self.findChild(QtWidgets.QComboBox, 'removeType_entry')
self.openCharacter_comboBox = self.findChild(QtWidgets.QComboBox, 'openCharacter_comboBox')

#scroll areas
self.scrollArea = self.findChild(QtWidgets.QScrollArea, 'scrollArea')
self.proficiencies_scrollArea = self.findChild(QtWidgets.QScrollArea, 'proficiencies_scrollArea')

#text edit areas
self.language_textArea = self.findChild(QtWidgets.QTextEdit, 'language_textArea')
self.misc_textArea = self.findChild(QtWidgets.QTextEdit, 'misc_textArea')
self.toolsAndEquipment_textArea = self.findChild(QtWidgets.QTextEdit, 'toolsAndEquipment_textArea')
self.weaponsAndArmor_textArea = self.findChild(QtWidgets.QTextEdit, 'weaponsAndArmor_textArea')
self.personalityTraits_textEdit = self.findChild(QtWidgets.QTextEdit, 'personalityTraits_textEdit')
self.ideals_textEdit = self.findChild(QtWidgets.QTextEdit, 'ideals_textEdit')
self.bonds_textEdit = self.findChild(QtWidgets.QTextEdit, 'bonds_textEdit')
self.flaws_textEdit = self.findChild(QtWidgets.QTextEdit, 'flaws_textEdit')
self.equipment_textArea = self.findChild(QtWidgets.QTextEdit, 'equipment_textArea')
self.FeaturesAndTraits_textArea = self.findChild(QtWidgets.QTextEdit, 'FeaturesAndTraits_textArea')
self.alliesAndOrganizations_textArea = self.findChild(QtWidgets.QTextEdit, 'alliesAndOrganizations_textArea')
self.miscNotes_textArea = self.findChild(QtWidgets.QTextEdit, 'miscNotes_textArea')
self.characterBackstory_textArea = self.findChild(QtWidgets.QTextEdit, 'characterBackstory_textArea')
self.addItemDescription = self.findChild(QtWidgets.QTextEdit, 'addItemDescription')
self.magicItemsBox_textEdit = self.findChild(QtWidgets.QTextEdit, 'magicItemsBox_textEdit')
self.weapons_textArea = self.findChild(QtWidgets.QTextEdit, 'weapons_textArea')
self.inspiration_entry = self.findChild(QtWidgets.QCheckBox, 'inspiration_entry')


for skill in skills:
	exec("""self.{skill}_checkBox = self.findChild(QtWidgets.QCheckBox, '{skill}_checkBox')""".format(skill=skill))
	exec("""self.{skill}Modifier_label = self.findChild(QtWidgets.QLabel, '{skill}Modifier_label')""".format(skill=skill))

self.success_checkBox1 = self.findChild(QtWidgets.QCheckBox, 'success_checkBox1')
self.success_checkBox2 = self.findChild(QtWidgets.QCheckBox, 'success_checkBox2')
self.success_checkBox3 = self.findChild(QtWidgets.QCheckBox, 'success_checkBox3')
self.fail_checkBox1 = self.findChild(QtWidgets.QCheckBox, 'fail_checkBox1')
self.fail_checkBox3 = self.findChild(QtWidgets.QCheckBox, 'fail_checkBox3')
self.fail_checkBox2 = self.findChild(QtWidgets.QCheckBox, 'fail_checkBox2')

#frames:
frameShadow = QtWidgets.QGraphicsDropShadowEffect()
frameShadow.setBlurRadius(30)
frameShadow.setOffset(2)
frameShadow.setColor(QtGui.QColor(30, 30, 30, 160))
self.frame = self.findChild(QtWidgets.QFrame, "frame")
#self.frame.setGraphicsEffect(frameShadow)

frameShadow13 = QtWidgets.QGraphicsDropShadowEffect()
frameShadow13.setBlurRadius(30)
frameShadow13.setOffset(2)
frameShadow13.setColor(QtGui.QColor(30, 30, 30, 160))
self.frame_13 = self.findChild(QtWidgets.QFrame, "frame_13")
#self.frame_13.setGraphicsEffect(frameShadow13)

self.statusBar().setStyleSheet("""background-color: white;
font: MS Shell Dlg 2, 8pt;
""")